# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <velocity> <velocity> <function> <initial C_1> <initial position> <initial position> 
0.22563 0.602738 0 0 0 0 0 0.22563 0.602738 

