# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.550781 0.0103346 0 1 0 0 1 

0.567488 0.0124484 1 1 0 0 1 

0.991816 0.233091 2 1 0 0 1 

0.711657 0.304893 3 1 0 0 1 

0.625866 0.320658 4 1 0 0 1 

