# This file was generated by the deal.II library.
# Date =  2020/1/24
# Time =  14:36:48
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <velocity> <velocity> <function> <initial C_1> <initial position> <initial position> 
0.0564076 0.957498 2 1.4648e-06 7.90918e-06 0 0 0.0564076 0.957498 

