# This file was generated by the deal.II library.
# Date =  2020/1/24
# Time =  14:36:48
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <velocity> <velocity> <function> <initial C_1> <initial position> <initial position> 
0.328399 0.375494 0 1.56672e-06 9.02908e-05 0 5.62518e-08 0.328399 0.375494 

0.675855 0.435603 1 2.55899e-06 0.000150278 0 1.49536e-11 0.675855 0.435603 

