# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <velocity> <velocity> <function> <initial C_1> <initial position> <initial position> 
0.328399 0.375494 0 0 0 0 5.62518e-08 0.328399 0.375494 

0.675855 0.435603 1 0 0 0 1.49536e-11 0.675855 0.435603 

