# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <adiabatic_temperature> <adiabatic_pressure> <adiabatic_density> <adiabatic_density_derivative> <density> 
0 0 0 0 3.30021e+09 1573 1585.63 3.29979e+09 3299.58 -4.18604e-06 3300.42 
100000 0 0 0 3.30021e+09 1573 1585.63 3.29979e+09 3299.58 -4.18604e-06 3300.42 

0 100000 0 0 1.07917e-07 1573 1573 0 3300 -4.15272e-06 3300 
100000 100000 0 0 -1.07888e-07 1573 1573 0 3300 -4.15272e-06 3300 


