# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <adiabatic_temperature> <adiabatic_pressure> <adiabatic_density> <adiabatic_density_derivative> <density> 
0 0 0 0 3.3e+09 1585.63 1585.63 3.3e+09 3300 0 3300 
100000 0 0 0 3.3e+09 1585.63 1585.63 3.3e+09 3300 0 3300 

0 100000 0 0 -1.86532e-09 1573 1573 0 3300 -4.15272e-06 3300 
100000 100000 0 0 1.86532e-09 1573 1573 0 3300 -4.15272e-06 3300 


