# This file was generated by the deal.II library.
# Date =  2020/11/18
# Time =  21:18:24
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <adiabatic_temperature> <adiabatic_pressure> <adiabatic_density> <adiabatic_density_derivative> <density> 
0 0 0 0 3.30021e+09 1573 1585.63 3.25689e+09 3256.68 -4.18604e-06 3300.42 
100000 0 0 0 3.30021e+09 1573 1585.63 3.25689e+09 3256.68 -4.18604e-06 3300.42 

0 100000 0 0 1.00583e-07 1573 1573 0 3257.1 -4.15272e-06 3300 
100000 100000 0 0 -9.68575e-08 1573 1573 0 3257.1 -4.15272e-06 3300 


