# This file was generated by the deal.II library.
# Date =  2026/4/30
# Time =  15:59:38
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position> 
0.15441 6.11835 0 0 0 0.149573 6.11967 

0.0806422 4.65979 1 0 0 0.0796325 4.69615 

