# This file was generated by the deal.II library.
# Date =  2024/10/1
# Time =  15:09:20
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> 
0.465603 0.736665 5 0 

0.603769 0.666159 6 0 

0.662439 0.626557 7 0 

0.486466 0.764985 8 0 

0.877698 0.782952 9 0 

