language: cpp
sudo: false
dist: trusty
before_install:
  - echo ${CMAKE_EXTRA_ARGS}
  - eval "${MATRIX_EVAL}"
  - echo ${MATRIX_EVAL}
  - echo ${CC}
  - echo ${CXX}
  - echo ${FC}
  - gcc --version
  - gcov --version
  - make --version
script:
  - gcc --version
  - gcov --version
  - gfortran --version
  - mkdir build
  - mkdir install
  - cmake . -G "${MAKE_FILE_GENERATOR}" ${CMAKE_EXTRA_ARGS} ${MAC_COMPILER_EXTRA}
  - make -j 2
  - ctest -VV
  - if [ "${RUN_COVERALLS}" = "TRUE" ]; then
      make indent;
      diff=$(git status | grep 'modified' --count);
      if [[ "$diff" -gt "0" ]]; then 
         git diff > diff.log; 
         cat diff.log; 
         return 1; 
      fi
    fi
after_success:
    - if [ "${RUN_COVERALLS}" = "TRUE" ]; then
        coveralls -i source -i app --gcov-options '\-lp'; 
      fi
    - if [ "${RUN_COVERALLS}" = "TRUE" ]; then
        bash <(curl -s https://codecov.io/bash);
      fi

before_script:
            - gcc --version
            - gcov --version

cache: 
  apt: true

matrix:
  include:
    - name: "linux gcc 6 coverage"
      sudo: true
      os: linux
      compiler: 
        - g++-6
      env: 
         - MAKE_FILE_GENERATOR="Unix Makefiles"
         - CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} -DCMAKE_BUILD_TYPE=Coverage"
         - RUN_COVERALLS="TRUE"
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && FC=gfortran && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-6 --slave /usr/bin/gcov gcov /usr/bin/gcov-6 && sudo update-alternatives --config gcc && gcc --version && gcov --version && mkdir astyle && cd astyle && wget 'https://sourceforge.net/projects/astyle/files/astyle/astyle 2.04/astyle_2.04_linux.tar.gz' && tar -zxvf astyle_2.04_linux.tar.gz && cd astyle/build/gcc && make && sudo make install && cd ../../../../ && pip install --user cpp-coveralls"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gfortran-6
            - cmake

    - name: "linux gcc 6 release"
      sudo: false
      compiler:
        - g++-6
      env:
         - MAKE_FILE_GENERATOR="Unix Makefiles"
         - CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} -DCMAKE_BUILD_TYPE=Release"
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && FC=gfortran"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gfortran
            - cmake

    - name: "linux gcc 4.9 debug"
      sudo: false
      compiler:
        - g++-4.9
      env:
         - MAKE_FILE_GENERATOR="Unix Makefiles"
         - CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} -DCMAKE_BUILD_TYPE=Debug"
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9 && FC=gfortran"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gfortran
            - cmake
       

    - name: "linux clang"
      sudo: false
      os: linux
      compiler: 
        - clang-3.6
      env: 
         - MAKE_FILE_GENERATOR="Unix Makefiles"
         - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6 && GC=gfortran" 
         - CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} -DCMAKE_BUILD_TYPE=Debug"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - gfortran 
            - cmake
    - name: "osx clang"
      sudo: false
      os: osx
      compiler: 
        - clang
      osx_image: xcode10
      env: 
         - MAKE_FILE_GENERATOR="Unix Makefiles"
         - MATRIX_EVAL="export PATH=$TRAVIS_ROOT/bin:$PATH && which clang && ls -lh /Applications/Xcode-10.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/ && ls -lh /Applications/Xcode-10.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ && brew install gcc || true  && brew link --overwrite gcc && brew install libomp || brew upgrade libomp || true  && export LDFLAGS="-L/Applications/Xcode-10.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib" && export CPPFLAGS="-I/Applications/Xcode-10.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include" && export CC=/Applications/Xcode-10.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang && export  CXX=/Applications/Xcode-10.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ && export FC=gfortran" 
         - CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} -DCMAKE_BUILD_TYPE=Debug -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include -lomp" -DOpenMP_CXX_LIB_NAMES="omp" -DOpenMP_omp_LIBRARY=/usr/local/opt/libomp/lib/libomp.dylib"

    - name: "windows debug"
      os: windows
      language: cpp 
      env:
         - MATRIX_EVAL="which gcc && which mingw32-make.exe && ln -s /c/ProgramData/chocolatey/bin/mingw32-make.exe /c/ProgramData/chocolatey/bin/make.exe && which make"
         - MAKE_FILE_GENERATOR="MinGW Makefiles"
         - FC=gfortran
         - CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS}  -DCMAKE_SH=CMAKE_SH-NOTFOUND -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_VERBOSE_MAKEFILE=ON"

    - name: "windows release"
      os: windows
      language: cpp 
      env:
         - MATRIX_EVAL="which gcc && which mingw32-make.exe && ln -s /c/ProgramData/chocolatey/bin/mingw32-make.exe /c/ProgramData/chocolatey/bin/make.exe && which make"
         - MAKE_FILE_GENERATOR="MinGW Makefiles"
         - FC=gfortran
         - CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS}  -DCMAKE_SH=CMAKE_SH-NOTFOUND -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_VERBOSE_MAKEFILE=ON"
