# This file was generated by the deal.II library.
# Date =  2024/8/28
# Time =  13:34:59
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.5 0.5 0 1 0 0 1 

