# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <density> <mass_error> <mass_error_face_integral> 
0 0 0 1 1.5 0 1 1 1 
0.5 0 0 1 1.5 0 1 1 1 

0 0.5 0 1 0.875 0 1.5 1 1 
0.5 0.5 2.91445e-17 1 0.875 0 1.5 1 1 


0.5 0 0 1 1.5 0 1 1 1 
1 0 0 1 1.5 0 1 1 1 

0.5 0.5 2.91445e-17 1 0.875 0 1.5 1 1 
1 0.5 0 1 0.875 0 1.5 1 1 


0 0.5 0 1 0.875 0 1.5 1 1 
0.5 0.5 2.91445e-17 1 0.875 0 1.5 1 1 

0 1 0 1 -2.55858e-13 0 2 1 1 
0.5 1 1.05681e-16 1 2.5796e-13 0 2 1 1 


0.5 0.5 2.91445e-17 1 0.875 0 1.5 1 1 
1 0.5 0 1 0.875 0 1.5 1 1 

0.5 1 1.05681e-16 1 2.5796e-13 0 2 1 1 
1 1 0 1 -2.60056e-13 0 2 1 1 


