# This file was generated by the deal.II library.
# Date =  2026/7/25
# Time =  14:55:45
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <damage_strain> <viscosity> <current_cohesions> <current_friction_angles> <current_yield_stresses> <current_yield_stress_prefactors> <plastic_yielding> 
0 0 0.05 -0.05 0.00024123 273 0.5 2.75e+20 1e+06 0 550000 0.55 1 
1 0 -0.05 -0.05 0.000170314 273 0.5 2.75e+20 1e+06 0 550000 0.55 1 

0 1 0.05 0.05 3.54582e-05 273 0.5 2.75e+20 1e+06 0 550000 0.55 1 
1 1 -0.05 0.05 -3.54582e-05 273 0.5 2.75e+20 1e+06 0 550000 0.55 1 


