# This file was generated by the deal.II library.
# Date =  2026/7/25
# Time =  14:55:45
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <damage_strain> <viscosity> <current_cohesions> <current_friction_angles> <current_yield_stresses> <current_yield_stress_prefactors> <plastic_yielding> 
0 0 0.05 -0.05 -2.66985e-18 273 0.100857 1e+18 1e+06 0 909228 0.909228 1 
1 0 -0.05 -0.05 -1.89735e-18 273 0.100857 1e+18 1e+06 0 909228 0.909228 1 

0 1 0.05 0.05 -4.06576e-19 273 0.100857 1e+18 1e+06 0 909228 0.909228 1 
1 1 -0.05 0.05 3.93023e-19 273 0.100857 1e+18 1e+06 0 909228 0.909228 1 


