# This file was generated by the deal.II library.
# Date =  2026/5/27
# Time =  17:16:59
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> 
0.664664 0.624404 7 0 

0.468924 0.736266 5 0 

0.606507 0.664588 6 0 

0.489582 0.764557 8 0 

0.878017 0.781807 9 0 

