# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.197658 0.356879 0 1 2 -1.85012e-07 1 

0.41228 0.36825 3 1 2 -1.97278e-07 1 

0.360136 0.467838 1 1 2 -2.81415e-07 1 

0.554434 0.0111377 2 1 2 -3.32606e-09 1 

0.712534 0.4761 4 0.999999 2 -8.77925e-07 0.999999 

