# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.0518614 0.76572 8 1 2 -1.65434e-07 1 

0.981939 0.633479 7 0.999999 2 -2.8314e-07 1 

0.990671 0.670719 6 0.999999 2 -3.65666e-07 1 

0.97115 0.737107 5 1 2 -2.83826e-07 1 

0.533167 0.787226 9 1 2 1.91224e-07 1 

