# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.197658 0.356879 0 1 2 1.83853e-07 1 

0.41228 0.36825 3 0.999999 2 -2.5611e-07 1 

0.360136 0.467838 1 1 2 2.88225e-07 1 

0.554434 0.0111377 2 1 2 -1.43799e-09 1 

0.712534 0.4761 4 0.999998 2 -1.48436e-06 0.999999 

