# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.483901 0.356879 0 1 0 0 1 

0.424461 0.467838 1 1 0 0 1 

0.532159 0.0111377 2 1 0 0 1 

0.675781 0.36825 3 1 0 0 1 

0.760335 0.4761 4 1 0 0 1 

