# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.484774 0.68981 5 1 0 0 1 

0.307304 0.811481 6 1 0 0 1 

0.599747 0.600343 7 1 0 0 1 

0.746935 0.635618 8 1 0 0 1 

0.549607 0.969555 9 1 0 0 1 

