# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.496935 0.737107 5 1 0 0 1 

0.649232 0.670719 6 1 0 0 1 

0.714982 0.633479 7 1 0 0 1 

0.520421 0.76572 8 1 0 0 1 

0.958714 0.787226 9 1 0 0 1 

