# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.0181717 0.635618 8 0.999999 2 -4.26554e-07 1 

0.488717 0.969555 9 1 2 -6.62889e-09 1 

0.800434 0.600343 7 0.999999 2 -6.45464e-07 0.999999 

0.864393 0.68981 5 1 2 -5.15565e-07 0.999999 

0.930265 0.811481 6 1 2 -2.43231e-07 1 

