# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.457998 0.233091 2 1 2 -9.95139e-08 1 

0.321444 0.304893 3 1 2 -1.01083e-07 1 

0.267182 0.320658 4 1 2 1.90427e-08 1 

0.57145 0.0103346 0 1 2 -3.29694e-10 1 

0.592385 0.0124484 1 1 2 -1.09465e-10 1 

