# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <velocity> <velocity> <function> <initial C_1> <initial position> <initial position> 
0.626778 0.197844 0 0 0 0 0.292012 0.626778 0.197844 

0.574699 0.453122 1 0 0 0 4.62924e-12 0.574699 0.453122 

