# This file was generated by the deal.II library.
# Date =  2020/1/24
# Time =  14:36:45
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <velocity> <velocity> <function> <initial C_1> <initial position> <initial position> 
0.682668 0.821918 2 1.24261e-05 -7.89639e-06 0 0 0.682668 0.821918 

