# This file was generated by the deal.II library.
# Date =  2020/1/24
# Time =  14:31:48
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <velocity> <velocity> <function> <initial C_1> <initial position> <initial position> 
0.412162 0.35922 0 -4.49954e-06 3.41793e-05 0 1.65479e-07 0.412162 0.35922 

