# This file was generated by the deal.II library.
# Date =  2022/6/20
# Time =  10:58:12
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <z> <id> <integrated strain invariant> <strainrate_0> <strainrate_1> <strainrate_2> <strainrate_3> <strainrate_4> <strainrate_5> <strainrate_6> <strainrate_7> <strainrate_8> 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 

0 0 0 1 0 0 0 0 0 0 0 0 0 0 

0 0 0 2 0 0 0 0 0 0 0 0 0 0 

0 0 0 3 0 0 0 0 0 0 0 0 0 0 

0 0 0 4 0 0 0 0 0 0 0 0 0 0 

0 0 0 5 0 0 0 0 0 0 0 0 0 0 

0 0 0 6 0 0 0 0 0 0 0 0 0 0 

0 0 0 7 0 0 0 0 0 0 0 0 0 0 

0 0 0 8 0 0 0 0 0 0 0 0 0 0 

0 0 0 9 0 0 0 0 0 0 0 0 0 0 

