# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <grain_size> 
42904.5 1207.85 0 8e-05 

5869.67 43793.3 1 8e-05 

28532.9 34407.1 2 8e-05 

2581.27 55301.1 3 8.00001e-05 

7195.5 59655.2 4 8.00001e-05 

40253.6 94392.4 5 8.00001e-05 

52629 73179.9 6 8.00001e-05 

70628.5 68396.2 7 8.00001e-05 

73541.3 72661.2 8 8.00001e-05 

91947.3 70854.9 9 8.00001e-05 

