/*
  Copyright (C) 2011 - 2026 by the authors of the ASPECT code.

  This file is part of ASPECT.

  ASPECT is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2, or (at your option)
  any later version.

  ASPECT is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with ASPECT; see the file LICENSE.  If not see
  <http://www.gnu.org/licenses/>.
*/


#include "aspect/postprocess/visualization/melt_fraction_ball_h2o.h"
#include <aspect/melt.h>

#include <deal.II/base/parameter_handler.h>
//#include "melt_fraction_ball_h2o.h"

//TOMS Algorithm 748, from boost library, is used to find the root of
//the iterative melt fraction problem.
#include <boost/math/tools/roots.hpp>

//Added solely for the cutoff effect test of line 257.
#include <iomanip>

namespace aspect
{
  namespace Postprocess
  {
    namespace VisualizationPostprocessors
    {
      //Eqn. 18 Katz et al (2003): melt water concentration.
      template <int dim>
      double
      MeltFractionBallH2O<dim>::calc_X_H2O(const double F) const
      {
        //The unit Katz et al (2003) works with is %wt, so ppms are converted to it.
        const double X_H2O_bulk = bulk_h2o_ppm / 10000.0;

        return X_H2O_bulk /
               (D_H2O + F * (1.0 - D_H2O));
      }
      //Eqn. 16 Katz et al (2003): deltaT.
      template <int dim>
      double
      MeltFractionBallH2O<dim>::calc_delta_T_H2O(const double F) const
      {
        return K_H2O * std::pow(calc_X_H2O(F), gamma_H2O);
      }

      //The water concentration of melt is bounded to the water saturation.
      template <int dim>
      double
      MeltFractionBallH2O<dim>::check_water_saturation(
        const double pressure,
        const double temperature,
        const double F,
        const double T_solidus,
        const double T_lherz_liquidus) const
      {
        const double pressure_GPa = pressure / 1.0e9;

        //Eqn. 17 Katz et al (2003): water saturation.
        const double X_H2O_sat = k1_H2O * std::pow(pressure_GPa, lambda_H2O) + k2_H2O * pressure_GPa;

        double F_corrected = F;

        //Eqn. 2 and eqn. 19 Katz et al (2003) are the anhydrous and hydrous version of the same eqn.
        //Eqn. 19 Katz et al (2003): with usage of water saturation instead of melt water concentration:
        if (calc_X_H2O(F) > X_H2O_sat)
          {
            const double T_prime =
              (temperature - T_solidus + K_H2O * std::pow(X_H2O_sat, gamma_H2O))
              / (T_lherz_liquidus - T_solidus);

            F_corrected = (T_prime > 0.0) ? std::pow(T_prime, beta1) : 0.0;
          }

        return F_corrected;
      }

      template <int dim>
      MeltFractionBallH2O<dim>::
      MeltFractionBallH2O ()
        :
        DataPostprocessorScalar<dim> ("melt_fraction",
                                      update_values | update_quadrature_points),
        Interface<dim>("")  // a fraction, so physical units "1"
      {}

      template <int dim>
      double
      MeltFractionBallH2O<dim>::
      melt_fraction (const double temperature,
                     const double pressure,
                     const std::string &melting_model) const
      {
        if (melting_model == "peridotite")
          {
            //Hydrous melting of peridotite after Katz, 2003.
            const double T_solidus  = A1 + 273.15
                                      + A2 * pressure
                                      + A3 * pressure * pressure;
            const double T_lherz_liquidus = B1 + 273.15
                                            + B2 * pressure
                                            + B3 * pressure * pressure;
            const double T_liquidus = C1 + 273.15
                                      + C2 * pressure
                                      + C3 * pressure * pressure;

            //Melt fraction after melting of all clinopyroxene.
            //Eqn. 7 Katz et al 2003.
            const double R_cpx = r1 + r2 * std::max(0.0, pressure);

            //When R_cpx gets to 0 ald lower, F_cpx_out = 1. This extension solves the problem generated by r2<0 in Ball et al (2022).
            //Eqn. 6 Katz et al 2003.
            const double F_cpx_out = (R_cpx <= 0.0 ? 1.0 : std::min(1.0, M_cpx / R_cpx));

            //Eqn. 9 Katz et al 2003.
            const double T_cpx_out = std::pow(F_cpx_out, 1.0 / beta1) * (T_lherz_liquidus - T_solidus) + T_solidus;

            //Hydrous version of eqn. 3 Katz et al 2003 (before cpx is out).
            const auto check_cpx = [&](const double F)
            {
              return (temperature - T_solidus + calc_delta_T_H2O(F))
                     / (T_lherz_liquidus - T_solidus);
            };

            //Root chasing. Eqn. 2 Katz et al 2003.
            const auto func_cpx = [&](const double F)
            {
              const double T_prime = check_cpx(F);
              return F - std::pow(T_prime, beta1);
            };

            //Hydrous version of eqn. 3 Katz et al 2003 (after cpx is out).
            const auto check_opx = [&](const double F)
            {
              return (temperature - T_cpx_out + calc_delta_T_H2O(F))
                     / (T_liquidus - T_cpx_out);
            };

            //Root chasing. Eqn. 8 Katz et al 2003.
            const auto func_opx = [&](const double F)
            {
              const double T_prime = check_opx(F);

              return F - F_cpx_out
                     - (1.0 - F_cpx_out) * std::pow(T_prime, beta2);
            };

            //Iterative algorithm to chase a root-finding bracket.
            const auto det_bracket =
              [&](const double start,
                  const double stop,
                  const unsigned int nb_incrmt,
                  const auto &func_check,
                  const auto &func,
                  double &bracket_low,
                  double &bracket_high) -> bool
            {
              double F = start;
              double incrmt = 0.0;

              for (unsigned int i = 0; i < nb_incrmt; ++i)
                {
                  incrmt = std::pow(10.0, -static_cast<double>(i + 1));

                  const double func_check_start = func_check(start);

                  if (func_check_start <= 0.0)
                    return false;

                  const double func_start = func(start);

                  while (F < stop)
                    {
                      const double func_check_F = func_check(F);

                      if (func_check_F >= 0.0)
                        {
                          const double func_F = func(F);

                          if (std::isfinite(func_F))
                            {
                              if (func_F * func_start < 0.0)
                                {
                                  bracket_low  = F - incrmt;
                                  bracket_high = F;
                                  return true;
                                }
                              else
                                F += incrmt;
                            }
                          else
                            break;
                        }
                      else
                        break;
                    }

                  F -= incrmt;
                }

              bracket_low  = F;
              bracket_high = F + incrmt;

              return true;
            };

            //Boost TOMS748 root finder within the bracket:
            const auto solve_root =
              [&](const auto &func,
                  const double a,
                  const double b) -> double
            {
              const double fa = func(a);
              const double fb = func(b);

              if (fa == 0.0)
                return a;

              if (fb == 0.0)
                return b;

              AssertThrow(fa * fb < 0.0,
              ExcMessage("Root is not bracketed."));

              boost::uintmax_t max_iter = 100;

              const auto tolerance =
              [](const double left, const double right)
              {
                return std::abs(right - left) < 1e-12;
              };

              const auto result =
                boost::math::tools::toms748_solve(func, a, b, fa, fb, tolerance, max_iter);

              return 0.5 * (result.first + result.second);
            };

            double bracket_low;
            double bracket_high;

            const bool valid_cpx = det_bracket(0.0, F_cpx_out, 9, check_cpx, func_cpx, bracket_low, bracket_high);

            double peridotite_melt_fraction;
            //Cutout effect test:
            //if (pressure > 7.99e9)
            //  std::cout << std::setprecision(17)
            //            << "pressure = " << pressure
            //            << std::endl;
            //

            if (pressure > 8.0e9)
              {
                peridotite_melt_fraction = 0.0;
              }
            else if (!valid_cpx)
              {
                peridotite_melt_fraction = 0.0;
              }
            else if (bracket_high < F_cpx_out)
              {
                peridotite_melt_fraction = solve_root(func_cpx, bracket_low, bracket_high);

                if (peridotite_melt_fraction > 0.0)
                  peridotite_melt_fraction = check_water_saturation(pressure, temperature, peridotite_melt_fraction, T_solidus, T_lherz_liquidus);
              }
            else
              {
                //cpx exhausted.
                double bracket_low_opx;
                double bracket_high_opx;

                const bool valid_opx = det_bracket(F_cpx_out, 1.0, 9, check_opx, func_opx, bracket_low_opx, bracket_high_opx);

                Assert(valid_opx, ExcInternalError());

                if (bracket_high_opx >= 1.0)
                  peridotite_melt_fraction = 1.0;
                else
                  peridotite_melt_fraction = solve_root(func_opx, bracket_low_opx, bracket_high_opx);
              }

            return peridotite_melt_fraction;
          }
        else if (melting_model == "pyroxenite")
          {
            // melting of pyroxenite after Sobolev et al., 2011
            const double T_melting = D1 + 273.15
                                     + D2 * pressure
                                     + D3 * pressure * pressure;

            const double discriminant = E1*E1/(E2*E2*4) + (temperature-T_melting)/E2;

            double pyroxenite_melt_fraction;

            if (temperature < T_melting || pressure > 1.3e10)
              pyroxenite_melt_fraction = 0.0;
            else if (discriminant < 0)
              pyroxenite_melt_fraction = 0.5429;
            else
              pyroxenite_melt_fraction = -E1/(2*E2) - std::sqrt(discriminant);

            return pyroxenite_melt_fraction;
          }
        else
          {
            // throw an error if the melting model is not implemented
            AssertThrow(false, ExcMessage("The selected melting model is not implemented."));
          }
      }

      template <int dim>
      void
      MeltFractionBallH2O<dim>::
      evaluate_vector_field(const DataPostprocessorInputs::Vector<dim> &input_data,
                            std::vector<Vector<double>> &computed_quantities) const
      {
        const unsigned int n_quadrature_points = input_data.solution_values.size();
        Assert (computed_quantities.size() == n_quadrature_points,    ExcInternalError());
        Assert (computed_quantities[0].size() == 1,                   ExcInternalError());
        Assert (input_data.solution_values[0].size() == this->introspection().n_components,           ExcInternalError());

        // in case the material model computes the melt fraction itself, we use that output
        if (MaterialModel::MeltFractionModel<dim>::is_melt_fraction_model(this->get_material_model()))
          {
            MaterialModel::MaterialModelInputs<dim> in(input_data,
                                                       this->introspection());
            MaterialModel::MaterialModelOutputs<dim> out(n_quadrature_points,
                                                         this->n_compositional_fields());
            MeltHandler<dim>::create_material_model_outputs(out);

            // Compute the melt fraction...
            this->get_material_model().evaluate(in, out);

            std::vector<double> melt_fractions(n_quadrature_points);
            MaterialModel::MeltFractionModel<dim>::as_melt_fraction_model(this->get_material_model())
            .melt_fractions(in, melt_fractions, &out);

            for (unsigned int q=0; q<n_quadrature_points; ++q)
              computed_quantities[q](0) = melt_fractions[q];
          }
        else
          for (unsigned int q=0; q<n_quadrature_points; ++q)
            {
              const double pressure    = input_data.solution_values[q][this->introspection().component_indices.pressure];
              const double temperature = input_data.solution_values[q][this->introspection().component_indices.temperature];
              std::vector<double> composition(this->n_compositional_fields());

              for (unsigned int c=0; c<this->n_compositional_fields(); ++c)
                composition[c] = input_data.solution_values[q][this->introspection().component_indices.compositional_fields[c]];

              // Calculate the melt fraction for the background material (peridotite)
              const double peridotite_melt_fraction = melt_fraction(temperature, pressure, "peridotite");
              // Calculate the melt fraction for the non peridotite compositional field
              double total_melt_fraction = 0.0;
              double total_comp_fraction = 0.0;

              for (const auto &model : melting_model)
                {
                  const unsigned int comp_index = this->introspection().compositional_index_for_name(model);
                  const double comp_melt_fraction = melt_fraction(temperature, pressure, model);
                  total_melt_fraction += composition[comp_index] * comp_melt_fraction;
                  total_comp_fraction += composition[comp_index];
                }
              if (total_comp_fraction > 1.0)
                AssertThrow(false, ExcMessage("The total fraction of non-peridotite compositional fields exceeds 1.0. "
                                              "Please check the input file and ensure that the sum of all compositional fields is less than or equal to 1.0."));
              total_melt_fraction += (1.0 - total_comp_fraction) * peridotite_melt_fraction;

              computed_quantities[q](0) = total_melt_fraction;
            }
      }



      template <int dim>
      void
      MeltFractionBallH2O<dim>::declare_parameters (ParameterHandler &prm)
      {
        prm.enter_subsection("Postprocess");
        {
          prm.enter_subsection("Visualization");
          {
            prm.enter_subsection("Melt fraction");
            {
              prm.declare_entry ("A1", "1085.7",
                                 Patterns::Double (),
                                 "Constant parameter in the quadratic "
                                 "function that approximates the solidus "
                                 "of peridotite. "
                                 "Units: $^\\circ\\text{C}$.");
              prm.declare_entry ("A2", "1.329e-7",
                                 Patterns::Double (),
                                 "Prefactor of the linear pressure term "
                                 "in the quadratic function that approximates "
                                 "the solidus of peridotite. "
                                 "$\\frac{^\\circ\\text{C}}{\\text{Pa}}$.");
              prm.declare_entry ("A3", "-5.1e-18",
                                 Patterns::Double (),
                                 "Prefactor of the quadratic pressure term "
                                 "in the quadratic function that approximates "
                                 "the solidus of peridotite. "
                                 "$\\frac{^\\circ\\text{C}}{\\text{Pa}^2}$.");
              prm.declare_entry ("B1", "1475.0",
                                 Patterns::Double (),
                                 "Constant parameter in the quadratic "
                                 "function that approximates the lherzolite "
                                 "liquidus used for calculating the fraction "
                                 "of peridotite-derived melt. "
                                 "Units: $^\\circ\\text{C}$.");
              prm.declare_entry ("B2", "8.0e-8",
                                 Patterns::Double (),
                                 "Prefactor of the linear pressure term "
                                 "in the quadratic function that approximates "
                                 "the  lherzolite liquidus used for "
                                 "calculating the fraction of peridotite-"
                                 "derived melt. "
                                 "$\\frac{^\\circ\\text{C}}{\\text{Pa}}$.");
              prm.declare_entry ("B3", "-3.2e-18",
                                 Patterns::Double (),
                                 "Prefactor of the quadratic pressure term "
                                 "in the quadratic function that approximates "
                                 "the  lherzolite liquidus used for "
                                 "calculating the fraction of peridotite-"
                                 "derived melt. "
                                 "$\\frac{^\\circ\\text{C}}{\\text{Pa}^2}$.");
              prm.declare_entry ("C1", "1780.0",
                                 Patterns::Double (),
                                 "Constant parameter in the quadratic "
                                 "function that approximates the liquidus "
                                 "of peridotite. "
                                 "Units: $^\\circ\\text{C}$.");
              prm.declare_entry ("C2", "4.50e-8",
                                 Patterns::Double (),
                                 "Prefactor of the linear pressure term "
                                 "in the quadratic function that approximates "
                                 "the liquidus of peridotite. "
                                 "$\\frac{^\\circ\\text{C}}{\\text{Pa}}$.");
              prm.declare_entry ("C3", "-2.0e-18",
                                 Patterns::Double (),
                                 "Prefactor of the quadratic pressure term "
                                 "in the quadratic function that approximates "
                                 "the liquidus of peridotite. "
                                 "$\\frac{^\\circ\\text{C}}{\\text{Pa}^2}$.");
              prm.declare_entry ("r1", "0.5",
                                 Patterns::Double (),
                                 "Constant in the linear function that "
                                 "approximates the clinopyroxene reaction "
                                 "coefficient. "
                                 "Units: non-dimensional.");
              prm.declare_entry ("r2", "8e-11",
                                 Patterns::Double (),
                                 "Prefactor of the linear pressure term "
                                 "in the linear function that approximates "
                                 "the clinopyroxene reaction coefficient. "
                                 "A negative value is expected in Ball et al 2022 implementation. "
                                 "Units: $\\frac{1}{\\text{Pa}}$.");
              prm.declare_entry ("beta1", "1.5",
                                 Patterns::Double (),
                                 "Exponent of the melting temperature in the melt "
                                 "fraction calculation before clinopyroxene exhaustion. "
                                 "Units: non-dimensional.");
              prm.declare_entry ("beta2", "1.2",
                                 Patterns::Double (),
                                 "Exponent of the melting temperature in the melt "
                                 "fraction calculation after clinopyroxene exhaustion. "
                                 "Units: non-dimensional.");
              prm.declare_entry ("Bulk H2O ppm", "0",
                                 Patterns::Double (0),
                                 "Bulk water content of the mantle source in ppm.");
              prm.declare_entry ("Mass fraction cpx", "0.15",
                                 Patterns::Double (),
                                 "Mass fraction of clinopyroxene in the "
                                 "peridotite to be molten. "
                                 "Units: non-dimensional.");
              prm.declare_entry ("D1", "976.0",
                                 Patterns::Double (),
                                 "Constant parameter in the quadratic "
                                 "function that approximates the solidus "
                                 "of pyroxenite. "
                                 "Units: $^\\circ\\text{C}$.");
              prm.declare_entry ("D2", "1.329e-7",
                                 Patterns::Double (),
                                 "Prefactor of the linear pressure term "
                                 "in the quadratic function that approximates "
                                 "the solidus of pyroxenite. "
                                 "Note that this factor is different from the "
                                 "value given in Sobolev, 2011, because they use "
                                 "the potential temperature whereas we use the "
                                 "absolute temperature. "
                                 "$\\frac{^\\circ\\text{C}}{\\text{Pa}}$.");
              prm.declare_entry ("D3", "-5.1e-18",
                                 Patterns::Double (),
                                 "Prefactor of the quadratic pressure term "
                                 "in the quadratic function that approximates "
                                 "the solidus of pyroxenite. "
                                 "$\\frac{^\\circ\\text{C}}{\\text{Pa}^2}$.");
              prm.declare_entry ("E1", "663.8",
                                 Patterns::Double (),
                                 "Prefactor of the linear depletion term "
                                 "in the quadratic function that approximates "
                                 "the melt fraction of pyroxenite. "
                                 "$\\frac{^\\circ\\text{C}}{\\text{Pa}}$.");
              prm.declare_entry ("E2", "-611.4",
                                 Patterns::Double (),
                                 "Prefactor of the quadratic depletion term "
                                 "in the quadratic function that approximates "
                                 "the melt fraction of pyroxenite. "
                                 "$\\frac{^\\circ\\text{C}}{\\text{Pa}^2}$.");
              // get the list of melting models that are not peridotite
              prm.declare_entry("List of melting compositions other than peridotite", " ",
                                Patterns::List(Patterns::Anything()),
                                "The list of compositional field names for melting composition "
                                "other than peridotite. Currently, only pyroxenite is implemented. "
                                "If a new melting model is added, the name of the default input "
                                "could be changed accordingly. "
                                "This input must be the same as the name of the corresponding "
                                "compositional field prescribed in the 'Compositional fields' "
                                "subsection so the melt fraction postprocessor can identify "
                                "which compositional field corresponds to which melting model. ");
              prm.declare_entry ("D H2O", "0.01",
                                 Patterns::Double (0),
                                 "Bulk partition coefficient of water.");
              prm.declare_entry ("K H2O", "43",
                                 Patterns::Double (0),
                                 "Water-induced melting temperature depression coefficient.");
              prm.declare_entry ("gamma H2O", "0.75",
                                 Patterns::Double (0),
                                 "Exponent for the water-induced melting temperature depression.");
              prm.declare_entry ("k1 H2O", "12",
                                 Patterns::Double (0),
                                 "Non-linear pressure coefficient for the melting water saturation.");
              prm.declare_entry ("k2 H2O", "1",
                                 Patterns::Double (0),
                                 "Linear pressure coefficient for the melting water saturation.");
              prm.declare_entry ("lambda H2O", "0.6",
                                 Patterns::Double (0),
                                 "Exponent for the non-linear pressure of the water saturation expression.");
            }
            prm.leave_subsection();
          }
          prm.leave_subsection();
        }
        prm.leave_subsection();
      }

      template <int dim>
      void
      MeltFractionBallH2O<dim>::parse_parameters (ParameterHandler &prm)
      {
        prm.enter_subsection("Postprocess");
        {
          prm.enter_subsection("Visualization");
          {
            prm.enter_subsection("Melt fraction");
            {
              A1              = prm.get_double ("A1");
              A2              = prm.get_double ("A2");
              A3              = prm.get_double ("A3");
              B1              = prm.get_double ("B1");
              B2              = prm.get_double ("B2");
              B3              = prm.get_double ("B3");
              C1              = prm.get_double ("C1");
              C2              = prm.get_double ("C2");
              C3              = prm.get_double ("C3");
              r1              = prm.get_double ("r1");
              r2              = prm.get_double ("r2");
              beta1           = prm.get_double ("beta1");
              beta2           = prm.get_double ("beta2");
              bulk_h2o_ppm    = prm.get_double ("Bulk H2O ppm");
              D_H2O           = prm.get_double ("D H2O");
              K_H2O           = prm.get_double ("K H2O");
              gamma_H2O       = prm.get_double ("gamma H2O");
              M_cpx           = prm.get_double ("Mass fraction cpx");
              k1_H2O          = prm.get_double ("k1 H2O");
              k2_H2O          = prm.get_double ("k2 H2O");
              lambda_H2O      = prm.get_double ("lambda H2O");
              D1              = prm.get_double ("D1");
              D2              = prm.get_double ("D2");
              D3              = prm.get_double ("D3");
              E1              = prm.get_double ("E1");
              E2              = prm.get_double ("E2");
              melting_model = Utilities::split_string_list(prm.get("List of melting compositions other than peridotite"));
              // Check if each melting model has an identically named compositional field
              for (const auto &model_name : melting_model)
                {
                  AssertThrow(this->introspection().compositional_name_exists(model_name),
                              ExcMessage("The compositional field '" + model_name + "' does not exist. "
                                         "Please ensure that the name of the compositional field matches "
                                         "the name of the melting model specified in 'List of melting compositions other than peridotite'."));
                }
            }
            prm.leave_subsection();
          }
          prm.leave_subsection();
        }
        prm.leave_subsection();
      }
    }
  }
}

// explicit instantiations
namespace aspect
{
  namespace Postprocess
  {
    namespace VisualizationPostprocessors
    {
      ASPECT_REGISTER_VISUALIZATION_POSTPROCESSOR(MeltFractionBallH2O,
                                                  "melt fraction ball h2o", // TODO write down equations here
                                                  "A visualization output object that generates output "
                                                  "for the melt fraction at the temperature and "
                                                  "pressure of the current point. If the material model computes "
                                                  "a melt fraction, this is the quantity that will be visualized. "
                                                  "Otherwise, a specific parametrization for batch melting "
                                                  "(as described in the following) will be used. "
                                                  "It does not take into account latent heat. "
                                                  "If 'List of melting compositions other than peridotite' is empty, "
                                                  "this postprocessor will visualize the melt fraction of peridotite "
                                                  "(calculated using the hydrous model of Katz et al., 2003). "
                                                  "If 'List of melting compositions other than peridotite' is not empty, "
                                                  "the postprocessor assumes that the melt fraction of these compositional fields "
                                                  "is determined by the chosen melting model that is not peridotite (currently "
                                                  "assumed to be pyroxenite using the model of Sobolev, 2011.) "
                                                  "The melt fraction is visualized for a mixture of peridotite and additional "
                                                  "compositional fields that have an associated melting model. It "
                                                  "assumes that the melting of different composition does not interact "
                                                  "with each other."
                                                  "Other melt models for the non-peridotite compositional field can be "
                                                  "added by adding a new instance of the melt_fraction function. "
                                                  "All the parameters that were used in these calculations "
                                                  "can be changed in the input file, including the bulk water "
                                                  "content of the mantle source (Bulk H2O ppm) and the mass "
                                                  "fraction of Cpx in peridotite (Mass fraction cpx) in the Katz melting model. "
                                                  "The corresponding $p$-$T$-diagrams can be generated by running "
                                                  "the tests melt\\_postprocessor\\_ball_h2o. "
                                                  "\n\n"
                                                  "Physical units: None.")
    }
  }
}
