# This file was generated by the deal.II library.
# Date =  2025/6/17
# Time =  16:20:48
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <z> <id> <velocity gradient_0> <velocity gradient_1> <velocity gradient_2> <velocity gradient_3> <velocity gradient_4> <velocity gradient_5> <velocity gradient_6> <velocity gradient_7> <velocity gradient_8> 
-0.273439 -0.479331 0.00997648 0 0 0 0 0 0 0 0 0 0 

-0.350103 -0.266367 0.216182 1 0 0 0 0 0 0 0 0 0 

0.298314 -0.140213 0.376733 2 0 0 0 0 0 0 0 0 0 

-0.358685 0.251282 0.228251 3 0 0 0 0 0 0 0 0 0 

-0.0379578 0.41282 0.0112068 4 0 0 0 0 0 0 0 0 0 

