# This file was generated by the deal.II library.
# Date =  2021/9/22
# Time =  10:40:15
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <porosity> <peridotite> <3> 
4.32363 33.4663 0 2 5 8 

4.69574 65.0347 1 2 5 8 

7.8263 77.5256 2 2 5 8 

4.56502 201.741 3 2 5 8 

3.2564 205.224 4 2 5 8 

4.70285 298.014 5 2 5 8 

2.1032 318.544 6 2 5 8 

1.50281 324.717 7 2 5 8 

8.83304 323.129 8 2 5 8 

6.05785 346.684 9 2 5 8 

