# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> 
0.287749 0.114493 0 

0.377791 0.108859 3 

0.288043 0.210443 1 

0.385548 0.215712 4 

0.298693 0.316434 2 

0.398858 0.319072 5 

0.468546 0.107512 6 

0.480355 0.20769 7 

0.500373 0.309804 8 

