# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.487742 0.698429 5 1 0 0 1 

0.596929 0.682878 6 1 0 0 1 

0.609926 0.533914 7 1 0 0 1 

0.581683 0.812881 8 1 0 0 1 

0.834856 0.898905 9 1 0 0 1 

