# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.439095 0.509238 5 1 0 0 1 

0.479214 0.995922 6 1 0 0 1 

0.648989 0.651374 7 1 0 0 1 

0.737742 0.542473 8 1 0 0 1 

0.698429 0.878219 9 1 0 0 1 

