# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <integrated strain_0> <integrated strain_1> <integrated strain_2> <integrated strain_3> 
0.948949 0.404992 5 0.887356 -0.7019 0.75426 0.534774 

