# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position> 
0.0569567 0.276217 2 0 0.00492534 0.906718 0.233091 

0.472019 0.00957782 0 1 1 0.503524 0.0103346 

0.483206 0.011345 1 1 1 0.518798 0.0124484 

0.552592 0.161827 4 0 2.66273e-06 0.572167 0.320658 

0.673687 0.13862 3 0 8.10222e-06 0.650597 0.304893 

