# This file was generated by the deal.II library.
# Date =  2022/5/21
# Time =  11:55:03
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <depth> <time> <viscosity> <log_viscosity> 
0 0 5.05e+25 25 
1e+06 0 5.05e+25 25 

0 0 5.05e+25 25 
1e+06 0 5.05e+25 25 


1e+06 0 5.5e+24 24.5 
2e+06 0 5.5e+24 24.5 

1e+06 0 5.5e+24 24.5 
2e+06 0 5.5e+24 24.5 


