# This file was generated by the deal.II library.
# Date =  2021/7/13
# Time =  5:52:13
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <depth> <time> <viscosity> <log_viscosity> 
0 0 5.05e+22 22 
1e+06 0 5.05e+22 22 

0 0 5.05e+22 22 
1e+06 0 5.05e+22 22 


1e+06 0 5.5e+21 21.5 
2e+06 0 5.5e+21 21.5 

1e+06 0 5.5e+21 21.5 
2e+06 0 5.5e+21 21.5 


