# This file was generated by the deal.II library.
# Date =  2019/5/13
# Time =  13:21:53
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <melt_presence> 
5 100 1 1 

5 200 0 1 

5 300 2 1 

