# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> 
0.28987 0.116826 0 

0.374816 0.112003 3 

0.289078 0.217264 1 

0.383282 0.224718 4 

0.29678 0.323828 2 

0.398769 0.327938 5 

0.461182 0.109379 6 

0.475619 0.212051 7 

0.501208 0.313832 8 

