# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> 
0.290004 0.116857 0 

0.374972 0.112002 3 

0.289307 0.217229 1 

0.38345 0.224721 4 

0.29691 0.323945 2 

0.398802 0.328039 5 

0.461337 0.109351 6 

0.475701 0.212145 7 

0.501172 0.313999 8 

