# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position> 
0.503524 0.0103346 0 1 1 0.503524 0.0103346 

0.518798 0.0124484 1 1 1 0.518798 0.0124484 

0.906719 0.233091 2 0 0.00492534 0.906718 0.233091 

0.650597 0.304893 3 0 8.10222e-06 0.650597 0.304893 

0.572167 0.320658 4 0 2.66273e-06 0.572167 0.320658 

