# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position> 
0.499333 0.0103123 0 1 1 0.503524 0.0103346 

0.513861 0.0124161 1 1 1 0.518798 0.0124484 

0.906349 0.218649 2 0 0.00492534 0.906718 0.233091 

0.569612 0.312231 4 0 2.66273e-06 0.572167 0.320658 

0.646934 0.293284 3 0 8.10222e-06 0.650597 0.304893 

