# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position> 
0.465603 0.736665 5 0 0 0.454298 0.737107 

0.603769 0.666159 6 0 0 0.593528 0.670719 

0.662439 0.626557 7 0 0 0.653636 0.633479 

0.486466 0.764985 8 0 0 0.475769 0.76572 

0.877698 0.782952 9 0 0 0.876456 0.787226 

