# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position> 
0.44318 0.68981 5 0 0 0.44318 0.68981 

0.280937 0.811481 6 0 0 0.280937 0.811481 

0.548289 0.600343 7 0 0 0.548289 0.600343 

0.682848 0.635618 8 0 0 0.682848 0.635618 

0.502451 0.969555 9 0 0 0.502451 0.969555 

