# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position> 
0.454298 0.737107 5 0 0 0.454298 0.737107 

0.593528 0.670719 6 0 0 0.593528 0.670719 

0.653636 0.633479 7 0 0 0.653636 0.633479 

0.475769 0.76572 8 0 0 0.475769 0.76572 

0.876456 0.787226 9 0 0 0.876456 0.787226 

