# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position> 
0.444262 0.352518 0 0 1.70119e-07 0.442382 0.356879 

0.400922 0.469257 1 0 3.73385e-12 0.388042 0.467838 

0.480316 0.0111001 2 1 1 0.4865 0.0111377 

0.618844 0.352756 3 0 1.72729e-08 0.617799 0.36825 

0.701754 0.459375 4 0 2.3731e-13 0.695098 0.4761 

