# This file was generated by the deal.II library.


#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position> 
0.292808 0.814084 6 0 0 0.280937 0.811481 

0.563069 0.593345 7 0 0 0.548289 0.600343 

0.459837 0.688852 5 0 0 0.44318 0.68981 

0.693476 0.625147 8 0 0 0.682848 0.635618 

0.505541 0.969511 9 0 0 0.502451 0.969555 

