# This file was generated by the deal.II library.
# Date =  2017/7/25
# Time =  18:07:20
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position> 
0.442382 0.356879 0 0 1.70119e-07 0.442382 0.356879 

0.388042 0.467838 1 0 3.73385e-12 0.388042 0.467838 

0.4865 0.0111377 2 1 1 0.4865 0.0111377 

0.617799 0.36825 3 0 1.72729e-08 0.617799 0.36825 

0.695098 0.4761 4 0 2.3731e-13 0.695098 0.4761 

