# This file was generated by the deal.II library.
# Date =  2017/7/25
# Time =  18:07:20
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position> 
0.442382 0.856879 5 0 0 0.442382 0.856879 

0.388042 0.967838 6 0 0 0.388042 0.967838 

0.4865 0.511138 7 0 2.5091e-14 0.4865 0.511138 

0.617799 0.86825 8 0 0 0.617799 0.86825 

0.695098 0.9761 9 0 0 0.695098 0.9761 

