# This file was generated by the deal.II library.
# Date =  2026/5/27
# Time =  17:16:58
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> 
0.501429 0.0103234 0 1 

0.516331 0.0124322 1 1 

0.906543 0.225785 2 0.00492534 

0.570997 0.316419 4 2.66273e-06 

0.6489 0.299057 3 8.10222e-06 

