# This file was generated by the deal.II library.
# Date =  2026/5/27
# Time =  17:16:59
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> 
0.498203 0.0103058 0 1 

0.512552 0.0124052 1 1 

0.90625 0.215737 2 0.00492534 

0.568323 0.30895 4 2.66273e-06 

0.645385 0.289718 3 8.10222e-06 

