# This file was generated by the deal.II library.
# Date =  2026/5/27
# Time =  17:16:58
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> 
0.459954 0.736917 5 0 

0.598674 0.668482 6 0 

0.65807 0.630067 7 0 

0.481123 0.765377 8 0 

0.877081 0.785107 9 0 

