# This file was generated by the deal.II library.
# Date =  2026/7/25
# Time =  14:55:51
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <damage_strain> <viscosity> <current_cohesions> <current_friction_angles> <current_yield_stresses> <current_yield_stress_prefactors> <plastic_yielding> 
0 0 0.05 -0.05 0 273 0.00107157 1e+18 1e+20 0 9.99036e+19 0.999036 0 
1 0 -0.05 -0.05 0 273 0.00107157 1e+18 1e+20 0 9.99036e+19 0.999036 0 

0 1 0.05 0.05 0 273 0.00107157 1e+18 1e+20 0 9.99036e+19 0.999036 0 
1 1 -0.05 0.05 0 273 0.00107157 1e+18 1e+20 0 9.99036e+19 0.999036 0 


