# This file was generated by the deal.II library.
# Date =  2026/7/28
# Time =  21:40:35
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <velocity> <velocity> <function> <function> <initial C_1> <initial position> <initial position> 
0.650666 0.733219 3 0 0 0 0 0 0.650666 0.733219 

0.482224 0.945979 4 0 0 0 0 0 0.482224 0.945979 

0.532906 0.95322 5 0 0 0 0 0 0.532906 0.95322 

0.876456 0.787226 6 0 0 0 0 0 0.876456 0.787226 

0.849035 0.835176 7 0 0 0 0 0 0.849035 0.835176 

0.813761 0.893708 8 0 0 0 0 0 0.813761 0.893708 

0.853739 0.994399 9 0 0 0 0 0 0.853739 0.994399 

