# This file was generated by the deal.II library.
# Date =  2026/7/28
# Time =  21:40:35
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <velocity> <velocity> <function> <function> <initial C_1> <initial position> <initial position> 
0.616592 0.407159 0 0 0 0 0 3.55318e-10 0.616592 0.407159 

0.903486 0.322835 1 0 0 0 8.38628e-08 6.27136e-07 0.903486 0.322835 

0.69021 0.449948 2 0 0 0 0 3.32007e-12 0.69021 0.449948 

