# This file was generated by the deal.II library.
# Date =  2026/7/28
# Time =  21:40:35
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <velocity> <velocity> <function> <function> <initial C_1> <initial position> <initial position> 
0.620471 0.396771 0 5.08386e-05 -0.000150325 0 0 3.55318e-10 0.616592 0.407159 

0.90338 0.305675 1 -1.98833e-06 -0.000243766 0 8.38628e-08 6.27136e-07 0.903486 0.322835 

0.694879 0.437422 2 6.29772e-05 -0.000181584 0 0 3.32007e-12 0.69021 0.449948 

