# This file was generated by the deal.II library.
# Date =  2022/9/29
# Time =  12:14:52
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <water_concentration> <viscosity> <strain_rate> 
0 70000 -0.0005 -0.0002 3e+09 1573 1 5.84876e+18 3.16698e-16 
10000 70000 -0.000400119 -0.0002 3e+09 1573 1 5.84896e+18 3.16698e-16 

0 80000 -0.0005 -0.0003 3e+09 1573 1 5.84876e+18 3.16698e-16 
10000 80000 -0.000400119 -0.0003 3e+09 1573 1 5.84896e+18 3.16698e-16 


