# This file was generated by the deal.II library.
# Date =  2022/9/29
# Time =  12:14:52
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <water_concentration> <viscosity> <strain_rate> 
90000 50000 0.000399937 7.77213e-14 3e+09 1573 100 5.92361e+16 3.16987e-16 
100000 50000 0.0005 8.37032e-13 3e+09 1573 100 5.92361e+16 3.16987e-16 

90000 60000 0.000399937 -0.0001 3e+09 1573 100 5.92361e+16 3.16987e-16 
100000 60000 0.0005 -0.0001 3e+09 1573 100 5.92361e+16 3.16987e-16 


