# This file was generated by the deal.II library.
# Date =  2022/9/29
# Time =  12:14:52
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <water_concentration> <viscosity> <strain_rate> 
60000 80000 0.000103535 -0.0003 3e+09 1573 100 5.92374e+16 3.09787e-16 
70000 80000 0.000199053 -0.0003 3e+09 1573 100 5.92358e+16 3.09787e-16 

60000 90000 0.000103535 -0.0004 3e+09 1573 100 5.92374e+16 3.09787e-16 
70000 90000 0.000199053 -0.0004 3e+09 1573 100 5.92358e+16 3.09787e-16 


