# This file was generated by the deal.II library.
# Date =  2022/9/29
# Time =  12:14:52
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <water_concentration> <viscosity> <strain_rate> 
40000 60000 -9.33093e-05 -0.0001 3e+09 1573 1 5.84894e+18 2.85383e-16 
50000 60000 -1.31927e-05 -9.99999e-05 3e+09 1573 100 5.92404e+16 2.85383e-16 

40000 70000 -9.33092e-05 -0.0002 3e+09 1573 1 5.84894e+18 2.85383e-16 
50000 70000 -1.31926e-05 -0.0002 3e+09 1573 100 5.92404e+16 2.85383e-16 


