# This file was generated by the deal.II library.
# Date =  2022/9/29
# Time =  12:14:52
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <water_concentration> <viscosity> <strain_rate> 
10000 20000 -0.000400119 0.0003 3e+09 1573 1 5.84896e+18 3.17834e-16 
20000 20000 -0.000299522 0.0003 3e+09 1573 1 5.84837e+18 3.17834e-16 

10000 30000 -0.000400119 0.0002 3e+09 1573 1 5.84896e+18 3.17834e-16 
20000 30000 -0.000299522 0.0002 3e+09 1573 1 5.84837e+18 3.17834e-16 


