# This file was generated by the deal.II library.
# Date =  2022/9/29
# Time =  12:14:52
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <water_concentration> <viscosity> <strain_rate> 
20000 10000 -0.000299522 0.0004 3e+09 1573 1 5.84837e+18 3.13291e-16 
30000 10000 -0.000201792 0.0004 3e+09 1573 1 5.85054e+18 3.13291e-16 

20000 20000 -0.000299522 0.0003 3e+09 1573 1 5.84837e+18 3.13291e-16 
30000 20000 -0.000201792 0.0003 3e+09 1573 1 5.85054e+18 3.13291e-16 


