# This file was generated by the deal.II library.
# Date =  2022/9/29
# Time =  12:14:52
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <water_concentration> <viscosity> <strain_rate> 
70000 90000 0.000199053 -0.0004 3e+09 1573 100 5.92358e+16 3.18788e-16 
80000 90000 0.000300252 -0.0004 3e+09 1573 100 5.92362e+16 3.18788e-16 

70000 100000 0.000199053 -0.0005 3e+09 1573 100 5.92358e+16 3.18788e-16 
80000 100000 0.000300252 -0.0005 3e+09 1573 100 5.92362e+16 3.18788e-16 


