# This file was generated by the deal.II library.
# Date =  2022/9/29
# Time =  12:14:52
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <water_concentration> <viscosity> <strain_rate> 
30000 50000 -0.000201792 -6.75021e-14 3e+09 1573 1 5.85054e+18 3.30328e-16 
40000 50000 -9.33092e-05 -6.59929e-14 3e+09 1573 1 5.84259e+18 3.30328e-16 

30000 60000 -0.000201792 -0.0001 3e+09 1573 1 5.85054e+18 3.30328e-16 
40000 60000 -9.33093e-05 -0.0001 3e+09 1573 1 5.84259e+18 3.30328e-16 


