# This file was generated by the deal.II library.
# Date =  2026/5/20
# Time =  12:26:03
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <id> <function> <initial C_1> <initial position> <initial position>
5.08092 0.106357 48 0 0 5.04283 0.152602

0.146787 5.79747 49 0 0 0.113109 5.79179

