name: linux

on:
  push:
    branches:
      - 'main'
      - 'aspect-*'
  pull_request:
      types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

concurrency:
  group: ${{ github.actor }}-${{ github.ref }}-docs
  cancel-in-progress: true

env:
  OMPI_MCA_btl_base_warn_component_unused: 0
  OMPI_MCA_mpi_yield_when_idle: 1
  OMPI_MCA_rmaps_base_oversubscribe: 1
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  OMPI_MCA_btl_vader_single_copy_mechanism: none

jobs:
  linux:
    #linux build including indent, examples and documentation
    name: indent+no-unity-build+documentation
    runs-on: [ubuntu-24.04]

    steps:
    - uses: actions/checkout@v7
    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ginggs/deal.ii-9.6.0-backports
        sudo apt-get update
        sudo apt-get install -yq --no-install-recommends texlive-plain-generic texlive-base texlive-latex-recommended texlive-latex-base texlive-fonts-recommended texlive-bibtex-extra lmodern texlive-latex-extra texlive-science graphviz python3-pip libdeal.ii-dev doxygen latexmk biber inkscape
        doxygen --version

        wget https://github.com/tjhei/astyle/releases/download/v2.04/astyle_2.04_linux.tar.gz
        tar xf astyle_2.04_linux.tar.gz
        cd astyle/build/gcc && make
        sudo USER=root make install
        cd
        rm -rf astyle*
        astyle --version
    - name: make indent
      run: |
        ./contrib/utilities/indent
        git diff > changes-astyle.diff
    - name: archive indent results
      uses: actions/upload-artifact@v7
      with:
        name: changes-astyle.diff
        path: changes-astyle.diff
        archive: false
    - name: check indentation
      run: |
        git diff --exit-code
    - name: citation list
      run: |
        cd doc
        latexmk -pdf -f citations-list.tex
        grep WARN citations-list.blg && echo "warnings found!" && exit 1
        echo "OK"
    - name: compile
      run: |
        mkdir build
        cd build
        /usr/bin/cmake -D CMAKE_BUILD_TYPE=Debug -D ASPECT_PRECOMPILE_HEADERS=OFF -D ASPECT_UNITY_BUILD=OFF \
                       -D CMAKE_CXX_FLAGS='-Werror' -D ASPECT_ADDITIONAL_CXX_FLAGS='-Wdeprecated-declarations' -D ASPECT_INSTALL_EXAMPLES=ON ..
        make -j 4
        ./aspect --test
    - name: doc
      run: |
        cd doc
        export OMPI_MCA_btl="self,vader"
        ./update_parameters.sh $GITHUB_WORKSPACE/build/aspect
        git diff > changes-parameters.diff
    - name: archive parameter documentation results
      uses: actions/upload-artifact@v7
      with:
        name: changes-parameters.diff
        path: doc/changes-parameters.diff
        archive: false
    - name: check parameter documentation
      run: |
        git diff --exit-code
